; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27023.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Roman\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
